name: CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pytest
    - name: Test with pytest
      run: pytest || python -m unittest discover
    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Déploiement simulé"